model:
  model_type: "resnet18"

dataset:
  name: "ImageNet-1K"
  path: "/share/seo/imagenet/"
  split: "train"
  train_dir: "/share/seo/imagenet/train/"
  test_dir: "/share/seo/imagenet/val/"
  samples: 512
  num_workers: 16
  num_classes: 1000

save:
  run_dir: "save/imagenet1K/resnet18/w8a8/"
  logger: "training.log"

quantization:
  wbit: 8
  abit: 8
  wqtype: adaround
  xqtype: lsq
  requires_grad: True

train:
  lr: 0.01
  momentum: 0.9
  epochs: 1
  weight_decay: 0.0001
  batch_size: 128
  loss_type: "mse"
  optim_type: sgd
  lr_sch: "step"
  mix_prec: True
  smoothing: 0.1
  schedule: [30, 60, 90]

prune:
  drate: 0.5
  prune_ratio: 0.85
  type: "element"
  warmup: 1
  final_epoch: 80
  prune_freq: 1000

t2c:
  swl: 32
  sfl: 26